/**
 * Error codes for structured error handling
 */
const ERROR_CODES = {
    INVALID_INPUT_TYPE: 'INVALID_INPUT_TYPE',
    EMPTY_INPUT: 'EMPTY_INPUT',
    INVALID_LINE_COUNT: 'INVALID_LINE_COUNT',
    INVALID_LINE_LENGTH: 'INVALID_LINE_LENGTH',
    INVALID_LINE_NUMBER: 'INVALID_LINE_NUMBER',
    CHECKSUM_MISMATCH: 'CHECKSUM_MISMATCH',
    INVALID_CHECKSUM_CHARACTER: 'INVALID_CHECKSUM_CHARACTER',
    SATELLITE_NUMBER_MISMATCH: 'SATELLITE_NUMBER_MISMATCH',
    INVALID_SATELLITE_NUMBER: 'INVALID_SATELLITE_NUMBER',
    INVALID_CLASSIFICATION: 'INVALID_CLASSIFICATION',
    VALUE_OUT_OF_RANGE: 'VALUE_OUT_OF_RANGE',
    INVALID_NUMBER_FORMAT: 'INVALID_NUMBER_FORMAT',
    SATELLITE_NAME_TOO_LONG: 'SATELLITE_NAME_TOO_LONG',
    SATELLITE_NAME_FORMAT_WARNING: 'SATELLITE_NAME_FORMAT_WARNING',
    // Deprecation and unusual value warnings
    CLASSIFIED_DATA_WARNING: 'CLASSIFIED_DATA_WARNING',
    STALE_TLE_WARNING: 'STALE_TLE_WARNING',
    HIGH_ECCENTRICITY_WARNING: 'HIGH_ECCENTRICITY_WARNING',
    LOW_MEAN_MOTION_WARNING: 'LOW_MEAN_MOTION_WARNING',
    DEPRECATED_EPOCH_YEAR_WARNING: 'DEPRECATED_EPOCH_YEAR_WARNING',
    REVOLUTION_NUMBER_ROLLOVER_WARNING: 'REVOLUTION_NUMBER_ROLLOVER_WARNING',
    NEAR_ZERO_DRAG_WARNING: 'NEAR_ZERO_DRAG_WARNING',
    NON_STANDARD_EPHEMERIS_WARNING: 'NON_STANDARD_EPHEMERIS_WARNING',
    NEGATIVE_DECAY_WARNING: 'NEGATIVE_DECAY_WARNING'
};

module.exports = { ERROR_CODES };
