import { format } from 'date-fns';

/**
 * Calendar Export Utilities
 *
 * Export satellite passes to iCalendar (.ics) format
 * for import into calendar applications
 */

/**
 * Export passes to iCalendar format
 *
 * @param {Array} passes - Array of pass objects
 * @param {string} satelliteName - Name of satellite
 */
export function exportToICS(passes, satelliteName) {
  const icsContent = generateICS(passes, satelliteName);
  downloadICS(icsContent, `${satelliteName}-passes.ics`);
}

/**
 * Generate iCalendar content
 *
 * @param {Array} passes - Array of pass objects
 * @param {string} satelliteName - Name of satellite
 * @returns {string} iCalendar formatted content
 */
function generateICS(passes, satelliteName) {
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Satellite Pass Predictor//TLE Parser Demo//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${satelliteName} Passes`,
    `X-WR-CALDESC:Satellite pass predictions for ${satelliteName}`,
    'X-WR-TIMEZONE:UTC'
  ];

  passes.forEach((pass, index) => {
    lines.push('BEGIN:VEVENT');
    lines.push(`UID:${generateUID(pass, index)}`);
    lines.push(`DTSTAMP:${formatICSDate(new Date())}`);
    lines.push(`DTSTART:${formatICSDate(pass.rise.time)}`);
    lines.push(`DTEND:${formatICSDate(pass.set.time)}`);
    lines.push(`SUMMARY:${satelliteName} Pass - Max El: ${pass.maxElevation.elevation.toFixed(1)}°`);

    const description = generatePassDescription(pass, satelliteName);
    lines.push(`DESCRIPTION:${description}`);

    lines.push(`LOCATION:Sky`);
    lines.push('STATUS:CONFIRMED');
    lines.push('TRANSP:TRANSPARENT');

    // Add alarm 5 minutes before pass
    lines.push('BEGIN:VALARM');
    lines.push('TRIGGER:-PT5M');
    lines.push('ACTION:DISPLAY');
    lines.push(`DESCRIPTION:${satelliteName} pass in 5 minutes`);
    lines.push('END:VALARM');

    lines.push('END:VEVENT');
  });

  lines.push('END:VCALENDAR');

  return lines.join('\r\n');
}

/**
 * Generate unique ID for calendar event
 *
 * @param {Object} pass - Pass object
 * @param {number} index - Pass index
 * @returns {string} Unique ID
 */
function generateUID(pass, index) {
  const timestamp = pass.rise.time.getTime();
  return `${timestamp}-${index}@satellite-pass-predictor.local`;
}

/**
 * Format date for iCalendar
 *
 * @param {Date} date - Date to format
 * @returns {string} Formatted date (YYYYMMDDTHHMMSSZ)
 */
function formatICSDate(date) {
  return format(date, "yyyyMMdd'T'HHmmss'Z'");
}

/**
 * Generate pass description for calendar event
 *
 * @param {Object} pass - Pass object
 * @param {string} satelliteName - Name of satellite
 * @returns {string} Description text
 */
function generatePassDescription(pass, satelliteName) {
  const lines = [
    `${satelliteName} Pass Information`,
    '',
    `Rise Time: ${format(pass.rise.time, 'HH:mm:ss')} (Az: ${pass.rise.azimuth.toFixed(1)}°)`,
    `Max Elevation: ${format(pass.maxElevation.time, 'HH:mm:ss')} (${pass.maxElevation.elevation.toFixed(1)}° at ${pass.maxElevation.azimuth.toFixed(1)}° Az)`,
    `Set Time: ${format(pass.set.time, 'HH:mm:ss')} (Az: ${pass.set.azimuth.toFixed(1)}°)`,
    `Duration: ${formatDuration(pass.duration)}`,
    '',
    'Generated by Satellite Pass Predictor (TLE Parser Demo)'
  ];

  return lines.join('\\n');
}

/**
 * Format duration in minutes and seconds
 *
 * @param {number} seconds - Duration in seconds
 * @returns {string} Formatted duration
 */
function formatDuration(seconds) {
  const minutes = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${minutes}m ${secs}s`;
}

/**
 * Download ICS file
 *
 * @param {string} content - ICS file content
 * @param {string} filename - Filename for download
 */
function downloadICS(content, filename) {
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

/**
 * Export passes to CSV format
 *
 * @param {Array} passes - Array of pass objects
 * @param {string} satelliteName - Name of satellite
 */
export function exportToCSV(passes, satelliteName) {
  const csvLines = [
    'Date,Rise Time,Rise Az,Max El Time,Max El,Max El Az,Set Time,Set Az,Duration'
  ];

  passes.forEach(pass => {
    const line = [
      format(pass.rise.time, 'yyyy-MM-dd'),
      format(pass.rise.time, 'HH:mm:ss'),
      pass.rise.azimuth.toFixed(1),
      format(pass.maxElevation.time, 'HH:mm:ss'),
      pass.maxElevation.elevation.toFixed(1),
      pass.maxElevation.azimuth.toFixed(1),
      format(pass.set.time, 'HH:mm:ss'),
      pass.set.azimuth.toFixed(1),
      formatDuration(pass.duration)
    ].join(',');

    csvLines.push(line);
  });

  const csvContent = csvLines.join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${satelliteName}-passes.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}
